Wish list
udaybansal19/Shimi pull request #3
Opened 2024-01-18 09:26 UTC by ayanjamil

tested Wish list page on Pixel 7 ( Screen Size = 6.31 inch ) , Pixel 3a( Screen Size = 5.6 inch) , Pixel 2(Screen Size = 5.0 inch) and Pixel 7 Pro ( Screen Size = 6.71 inch)
![Screenshot from 2024-01-18 14-52-53](https://github.com/udaybansal19/Shimi/assets/102759044/3195f9fc-e18a-4210-a37d-2a16eeffe323)
![Screenshot from 2024-01-18 14-46-11](https://github.com/udaybansal19/Shimi/assets/102759044/cbb2e183-6bc4-4ad7-bdc2-3118fc7b3e8
![Screenshot from 2024-01-16 22-36-44](https://github.com/udaybansal19/Shimi/assets/102759044/8418271c-8e05-4746-960c-0c1828c33eb2)
e)
![Screenshot from 2024-01-18 14-36-39](https://github.com/udaybansal19/Shimi/assets/102759044/92008a8c-1bd7-4756-b9a5-a7dca00a3465)

2024-01-18 17:45 UTC, udaybansal19 commented
@ayanjamil you can check in the screenshot that the distance between the product image and the view button is different on different screens. It should be constant across screens according to design

2024-01-21 14:03 UTC, ayanjamil commented
•  Top Navigation bar 
• Counter  for the number of wishlist items
• Formated code 
• Fixed padding and margin values 
• Added usable image files in constants and used in the home screen.
![Screenshot from 2024-01-21 19-29-00](https://github.com/udaybansal19/Shimi/assets/102759044/2531ed36-7e41-463c-ac85-34d9158bccd5)
![Screenshot from 2024-01-21 19-21-57](https://github.com/udaybansal19/Shimi/assets/102759044/afcb99fe-9d18-47ed-95c9-f849ad42de69)


![Screenshot from 2024-01-21 19-29-55](https://github.com/udaybansal19/Shimi/assets/102759044/5451bc62-2c7f-47c3-94b1-eef1f77e85e9)

2024-01-21 17:20 UTC, udaybansal19 requested changes

2024-01-21 17:20 UTC, udaybansal19 commented on components/CardWishList.js
> +    marginTop:'17%',
margins should me absolute

2024-01-21 17:20 UTC, udaybansal19 commented on components/CardWishList.js
> +    borderRadius:20,
incorrect linting

2024-01-21 17:20 UTC, udaybansal19 commented on components/CardWishList.js
> +                    <Image source={require("../assets/imgs/bin.png")} style={styles.logo} />
check for trash icon in icon libraries

2024-01-21 17:20 UTC, udaybansal19 commented on screens/WishList.js
>      var wishlistCards = [];
create a constant array and loop over the elements using .map.

2024-01-21 17:20 UTC, udaybansal19 commented on .vscode/settings.json
> +  "editor.defaultFormatter": "esbenp.prettier-vscode",
this file shouldn't not be committed. add it to .gitignore if needed

2024-01-21 17:20 UTC, udaybansal19 commented on assets/imgs/def.png
these files can be removed

2024-01-21 17:20 UTC, udaybansal19 commented on components/CardWishList.js
> +              uri: "https://encrypted-tbn2.gstatic.com/favicon-tbn?q=tbn:ANd9GcSrR7Ml_19H_B-zDu_Z_bQZGw0QqQ9U4wrcsyIsLYTUdUbRnR8dQRl2hFbwwMTnrsx4dn8RSieDAX0xgOMr90CKQT2BqGauj6jT9xLf-SQOorNViw",
this should be sent throught props

2024-01-21 17:20 UTC, udaybansal19 commented on components/CardWishList.js
> +            Mango
this as well

2024-01-21 17:20 UTC, udaybansal19 commented on components/CardWishList.js
> +                    source={require("../assets/imgs/bin.png")}
please remove unused code

2024-01-21 17:20 UTC, udaybansal19 commented on components/Header.js
> +    if (title != "home") {
why is this check needed?

2024-01-22 07:30 UTC, udaybansal19 commented on screens/WishList.js
> +    for (let i = 0; i < this.state.itemCount; i++) {
use `usables.map` to display all items from constants array

2024-01-22 16:35 UTC, udaybansal19 commented on screens/WishList.js
> +    this.setState({ itemCount: 23 });
this is not needed now

2024-01-22 17:16 UTC, udaybansal19 approved these changes

2024-01-23 13:13 UTC, merged